# Generated by Django 2.2 on 2021-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logandregvalidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
